= 信息安全复习
:toc:
== MAC模型

Lattice模型：Read-down write-down

BLP模型：read-down write-up （打小报告系统）

Biba模型：write-down read-up （上传下达，学习领导指示）

== 旁路攻击

从密码系统的物理实现中获取信息。例如缓存攻击、计时攻击等。

== PDR PPDR PDRR PPDRR WPDRRC

PDR：防护-检测-响应

PPDR：安全策略-防护-检测-响应

PDRR：防护-检测-响应-恢复

PPDRR：安全策略-防护-检测-响应-恢复

WPDRRC：预警-保护-检测-响应-恢复-反击

== 公共安全和个人隐私保护

网络安全是公共安全的重要组成部分，收集个人信息用于社会管理十分常见，但个人隐私的保护也十分重要。公共安全需要所有人的共同参与。

== 公钥证书与属性证书

一个系统中，每个用户只有一张合法的公钥证书。

多个应用可使用同一张属性证书，同一应用的不同操作可颁发不同的属性证书。

== APT攻击 0day攻击

APT攻击指技术高级、持续时间长、威胁性大的攻击

0day攻击指利用尚未公开的、没有补丁的漏洞进行的攻击

== ARP欺骗

将不正确的ARP解析发送给请求主机，进而伪装成接收主机，获取发送方发送的所有内容。

由于ARP是采用广播形式发送，因此ARP具有天然的漏洞，任何一个主机都可以发送ARP响应。

== OSI安全体系结构

* 应用层协议：SSH等。
* 传输层协议：SSL TLS
* 网络层安全协议：IPSec

== 入侵检测系统IDS

通过对计算机网络或计算机系统中的若干个关键点收集信息并对其进行分析，从中发现网络或系统中是否有违反安全策略的行为和被攻击的迹象。

== 恶意代码防范

基本措施：软件可信验证

* 软件特征可信
* 软件身份可信
* 软件能力可信
* 软件运行环境可信

== 软件著作人权

指作者对其创作的作品享有的人身权和财产权。人身权包括发表权、署名权、修改权、保护作品完成权等；财产权包括作品的使用权和获得报酬权。

违反软件著作权的行为：售卖盗版软件、抄袭代码等

== 信息内容安全

为什么信息内容安全越发重要：

* 信息社会信息内容更加丰富
* 信息内容安全事关重大，关系国家安全、公共安全、文化安全

信息内容定义和面临的威胁：

信息内容包括文字、图像、音频、视频

面临的威胁：网络低俗信息、反动信息、诈骗信息、
侵害隐私权的信息、侵害知识产权的信息等

== 公钥基础设施PKI

PKI是一套软硬件系统和安全策略的集合，提供了一整套安全机制，使用户在不知道对方身份或分布地点的情况下，以数字证书为基础，通过一系列的信任关系进行网络通信或网络交易。

PKI的基本结构：注册授权中心和数字证书库

PKI提供的安全服务：可认证性、不可抵赖性、机密性、数据完整性

== 授权管理基础设施PMI

PMI指全面支持授权服务和进行授权管理的基础设施，它建立在PKI提供的可信身份认证服务的基础上，以属性证书的形式来实现授权管理。

== 散列函数 数字签名 消息认证 信息隐藏

散列函数是从明文到密文的不可逆映射，将任意长度的输入转换为固定长度的输出。用于完整性验证和保护口令等。

数字签名：以电子形式存在于数据信息中的、或作为附件、或逻辑上与之有关联的数据，可用于辨别签署人的真实身份，并标明签署人对数据信息内容认可的技术。应用：直接对消息的签名，对压缩消息的签名，它们又分别包括确定性签名和随机化签名。

消息认证：指接收方能验证消息的真实性、所发消息的内容未修改，以及消息的顺序性和及时性。

消息认证和数字签名的区别：
当收发双方没有利害冲突时，消息认证是足够的；但当收发双方有利害冲突时，需借助数字签名技术。

信息隐藏：
将机密信息置于公开信息载体中进行发送的方法。

信息隐藏与加密：
加密保护的是信息内容本身，而信息隐藏可以掩盖机密信息的存在。

== 灾难恢复在PDRR模型中的地位与作用

PDRR，即防护-检测-响应-恢复安全模型，灾难恢复是重要组成部分，完整的备份和恢复策略可以保证系统的可用性。
